# Generated by Django 5.0.6 on 2024-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='статус платежа'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id сессии'),
        ),
    ]
