# Generated by Django 5.0.6 on 2024-07-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payments_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment',
        ),
    ]
