# Generated by Django 5.0.6 on 2024-06-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curse',
            new_name='Course',
        ),
    ]
