# Generated by Django 5.0.6 on 2024-06-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_lesson_curse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='curse',
            new_name='course',
        ),
    ]
