# Generated by Django 5.0.6 on 2024-07-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='стоимость курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='стоимость курса'),
        ),
    ]
